Feature/basic app settings
Chernovolos/test-app pull request #2
Opened 2021-07-26 15:23 UTC by Chernovolos

2021-07-26 15:57 UTC, zanusilker requested changes

2021-07-26 15:57 UTC, zanusilker commented on src/App.js
> +    return (
```suggestion
    return <div className="App">
```

2021-07-26 15:57 UTC, zanusilker commented on src/actions/actions.js
> +export const GET_USER_START = 'GET_USER_START';
META: `${prefix}META`,
    CLEAR: `${prefix}CLEAR`,

2021-07-26 15:57 UTC, zanusilker commented on src/App.js
>  function App() {
use same logic

2021-07-26 15:57 UTC, zanusilker commented on src/components/header.js
> +        <section className='mb-5'>
```suggestion
        <section className="mb-5">
```

2021-07-26 15:57 UTC, zanusilker commented on src/components/layout.js
> +                token?
compress

2021-07-26 15:57 UTC, zanusilker commented on src/constants/route.js
> +export const ROUTS = {
```suggestion
export const ROUTES = {
```

2021-07-26 15:57 UTC, zanusilker commented on src/components/header.js
> +                        <Link to='/' className='text-decoration-none'>test app</Link>
```suggestion
                        <Link to={ROUTES} className='text-decoration-none'>test app</Link>
```

2021-07-26 15:57 UTC, zanusilker commented on src/index.js
> +      <BrowserRouter>
connect history

2021-07-26 15:57 UTC, zanusilker commented on src/private/user-page/reducer.js
> +    preloader: false,
```suggestion
    initialized: false,
        disabled: false,
            errorMessage: null,
```

2021-07-26 15:57 UTC, zanusilker commented on src/private/user-page/reducer.js
> +            return {
```suggestion
            return state
```

2021-07-26 15:57 UTC, zanusilker commented on src/private/user-page/saga.js
> +function* workerUser(){
```suggestion
function* initializeSaga(){
```

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +let LoginForm = (props) => {
```suggestion
let LoginForm = ({ ... }) => {
```

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +    const FieldInput = ({ input, meta, type, placeholder, min, max }) => {
should be outside of component

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +                type={type}
🌲

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +                value={input.value}
```suggestion
                {... input}
```

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +            <Container>
```suggestion
            <Container tag="section">
```

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +                            <FormGroup className='mb-3'>
Move to FieldInput

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +                                    type='password'
disabled

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/index.js
> +                                <Button type='button' className='btn btn-danger text-uppercase' disabled={pristine || submitting} onClick={reset}>
```suggestion
                                <Button color="danger" type='button' className='btn text-uppercase' disabled={pristine || submitting} onClick={reset}>
```

2021-07-26 15:57 UTC, zanusilker commented on src/public/login/saga.js
> +        localStorage.setItem('TOKEN', userToken);
```suggestion
        yield call(localStorage.setItem, 'TOKEN', userToken);
```

2021-07-26 15:57 UTC, zanusilker commented on src/reducers/index.js
> +    login: loginReducer,
```suggestion
    login,
```

2021-08-02 08:40 UTC, zanusilker commented on src/actions/types.js
> +const SET_USER_VALUE = 'SET_USER_VALUE';
```suggestion
export const SET_USER_VALUE = 'SET_USER_VALUE';
```

2021-08-02 08:41 UTC, zanusilker commented on src/actions/types.js
> +const SET_USER_VALUE = 'SET_USER_VALUE';
src/public/sign-in
**- types
- action
- reducer**
- saga
- index

2021-08-02 08:42 UTC, zanusilker commented on src/private/index.js
> +import React from 'react';
// outsource dependencies
....

// local dependencies

2021-08-02 08:43 UTC, zanusilker commented on src/private/index.js
> +const PrivateLayout = () => {
use one oof Functional or Arrow functional components

2021-08-02 08:44 UTC, zanusilker commented on src/private/user-page/index.js
> +    dispatch(getUserStart());
```suggestion
    dispatch(initialize());
    return () => clear()
```

META
CLEAR
INITIALIZE

2021-08-02 08:45 UTC, zanusilker commented on src/private/user-page/saga.js
> +  instance.defaults.headers.common.Authorization = `Bearer ${JSON.parse(token)}`;
?

2021-08-02 08:45 UTC, zanusilker commented on src/private/user-page/saga.js
> +  return instance.get('auth/users/me');
```suggestion
  return instance('auth/users/me');
```

2021-08-02 08:47 UTC, zanusilker commented on src/public/login/saga.js
> +function * watcherUserAuthorization () {
```suggestion
export default function * () {
```

2021-08-02 08:47 UTC, zanusilker commented on src/public/login/saga.js
> +function * workerUserAuthorization ({ payload }) {
```suggestion
function * initializeSaga ({ payload }) {
```

2021-08-02 08:49 UTC, zanusilker commented on src/store.js
> +import { rootWatcher } from '../src/saga/index';
```suggestion
import { rootWatcher } from '../src/saga';
```

2021-08-03 11:31 UTC, zanusilker requested changes

2021-08-03 11:31 UTC, zanusilker commented on src/App.js
> +    return dispatch(clear());
Check it please

2021-08-03 11:31 UTC, zanusilker commented on src/App.js
> +      { preloader ? <Preloader/>: <Layout/> }
```suggestion
      { preloader ? <Preloader/> : <Layout/> }
```

2021-08-03 11:31 UTC, zanusilker commented on src/App.js
>    return (
```suggestion
  return <div
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/field-input.js
> +      { touched && invalid && <span className="text-danger">{ error }</span> }
```suggestion
      { meta.touched && mata.invalid && <span className="text-danger">{ meta.error }</span> }
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/field-input.js
> +  const { input, meta: { touched, error, invalid }, type, placeholder, name, label } = props;
```suggestion
  const { input, meta, type, placeholder, name, label } = props;
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/header.js
> +              <Button onClick={signIn}>sign out</Button>
```suggestion
              <Button onClick={**signIn**}>**sign out**</Button>
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/layout.js
> +  return (
```suggestion
  return <>
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/layout.js
> +        <Route path={ROUTES.HOME} component={Pages}/>
```suggestion
        <Route path={ROUTES.HOME} component={Home} />
```

2021-08-03 11:31 UTC, zanusilker commented on src/components/preloader.js
> +  return <Spinner type="grow" color="info"/>;
Why doo you need another component for it?

2021-08-03 11:31 UTC, zanusilker commented on src/components/header.js
> +import { Button, Container, Nav, Navbar, NavbarBrand, NavItem, } from 'reactstrap';
```suggestion
import { Button, Container, Nav, Navbar, NavbarBrand, NavItem } from 'reactstrap';
```

2021-08-03 11:31 UTC, zanusilker commented on src/index.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
```suggestion
// styles
import 'bootstrap/dist/css/bootstrap.min.css';
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/index.js
> +  const { user, preloader } = useSelector(state => state.pagesReducer.user);
reducer.js

export const selector = state => state.pagesReducer.user;

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +const GET_USER_START = 'GET_USER_START';
```suggestion
export const GET_USER_START = 'GET_USER_START';
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +export const USER = { GET_USER_START, };
```suggestion
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +export const INITIALIZE = 'USER-EDIT/INITIALIZE';
```suggestion
export const INITIALIZE = '???/INITIALIZE';
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +    case INITIALIZE:
```suggestion
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +  yield takeEvery(USER.GET_USER_START, initializeSaga);
```suggestion
  yield takeEvery(USER.ITIALIZE, initializeSaga);
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +  yield put({ type: META, payload: { preloader: true } });
```suggestion
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    yield put({ type: META, payload: { preloader: false } });
```suggestion
    yield put({ type: META, payload: { initialized: false } });
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    yield call(push, `${ROUTES.USER}`);
```suggestion
    yield call(history.push, ROUTES.USER);
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    if (error) {
```suggestion
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +            onSubmit={onSubmit}
🌲

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +            form={'sign-in-form'}
```suggestion
            form='sign-in-form'
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +              </Button>{ ' ' }
```suggestion
              </Button>
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +              <Button onClick={resetForm} type="button" color="danger" className="text-uppercase">
```suggestion
              <Button onClick={resetForm} type="reset" color="danger" className="text-uppercase">
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +export const LOGIN = { SET_USER_VALUE, };
```suggestion
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +export const setUserValue = (valueUser) => ({ type: LOGIN.SET_USER_VALUE, payload: valueUser });
```suggestion
export const setUserValue = valueUser => ({ type: LOGIN.SET_USER_VALUE, payload: valueUser });
```

2021-08-03 11:31 UTC, zanusilker commented on src/pages/public/sign-in/saga.js
> +    yield put({ type: META, payload: { error } });
```suggestion
    yield put({ type: META, payload: { error: error.message } });
```

2021-08-03 11:31 UTC, zanusilker commented on src/reducers/index.js
> +  pagesReducer,
```suggestion
  pages: pagesReducer,
```

2021-08-04 08:36 UTC, zanusilker requested changes

2021-08-04 08:36 UTC, zanusilker commented on src/App.js
> +  const { initialized } = useSelector(state => selector(state).signIn);
```suggestion
  const { initialized } = useSelector(selector);
```

2021-08-04 08:36 UTC, zanusilker commented on src/App.js
> +    return () => { dispatch(clear()); };
```suggestion
    return () => dispatch(clear());
```

2021-08-04 08:36 UTC, zanusilker commented on src/App.js
> +  return <div className="App">{ initialized ? <Spinner type="grow" color="info"/> : <Layout/> }</div>;
```suggestion
  return <div className="App">
  { initialized ? <Spinner type="grow" color="info"/> : <Layout/> }
  </div>;
```

2021-08-04 08:36 UTC, zanusilker commented on src/components/field-input.js
> +  name: PropTypes.string,
```suggestion
  name: PropTypes.string.isRequired,
```

2021-08-04 08:36 UTC, zanusilker commented on src/components/header.js
> +            <Button onClick={signOut}> sign out </Button>
```suggestion
            <Button onClick={dispatch action to saga signOut}> sign out </Button>
```

2021-08-04 08:36 UTC, zanusilker commented on src/components/layout.js
> +  return <><Header/><Pages/></>;
```suggestion
  return <>
  <Header/>
  <Pages/>
  </>;
```

2021-08-04 08:36 UTC, zanusilker commented on src/index.js
> +      closeOnToastrClick/>
```suggestion
      closeOnToastrClick
      />
```

2021-08-04 08:36 UTC, zanusilker commented on src/index.js
> +      timeOut={4000}
🌲

2021-08-04 08:36 UTC, zanusilker commented on src/pages/index.js
> +    <Route path={ROUTES.LOGIN} component={Public}/>
```suggestion
    <Route path={ROUTES.PUBLIC} component={Public}/>
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/index.js
> +    <Route path={ROUTES.USER} component={Private}/>
```suggestion
    <Route path={ROUTES.PRIVATE} component={Private}/>
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +export const initialize = () => ({ type: INITIALIZE });
split

2021-08-04 08:36 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +  const { data } = useSelector(state => selector(state));
```suggestion
  const { data } = useSelector(selector);
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +  const resetForm = () => dispatch(reset('sign-in-form'));
const FORM_NAME = 'sign-in-form';

2021-08-04 08:36 UTC, zanusilker commented on src/pages/public/sign-in/saga.js
> +    localStorage.removeItem('TOKEN');
only status 401

2021-08-04 08:36 UTC, zanusilker commented on src/pages/reducer.js
> +  signIn,
```suggestion
  public,
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/reducer.js
> +  user,
```suggestion
  private,
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/saga.js
> +  yield put({ type: META, payload: { initialized: true } });
```suggestion
```

2021-08-04 08:36 UTC, zanusilker commented on src/pages/saga.js
> +    yield put({ type: META, payload: { initialized: false } });
```suggestion
    yield put({ type: META, payload: { initialized: true } });
```

2021-08-05 08:45 UTC, zanusilker commented on src/App.js
> +    { errorMessage ? <Col>{ errorMessage }</Col> : null }
Container > Row > Col

2021-08-05 08:47 UTC, zanusilker commented on src/index.js
> +      getState={(state) => state.toastr}
create selector

2021-08-05 08:48 UTC, zanusilker commented on src/index.js
> +      newestOnTop={false}
what is the default value?

2021-08-05 08:48 UTC, zanusilker commented on src/pages/private/index.js
> +
```suggestion
```

2021-08-05 08:49 UTC, zanusilker commented on src/pages/private/reducer.js
> +import userReducer from './user-page/reducer';
local dependencies

2021-08-05 08:50 UTC, zanusilker commented on src/pages/private/sign-out/saga.js
> +import { SIGN_OUT } from '../../public/sign-in/reducer';
Parent or it own

2021-08-05 08:50 UTC, zanusilker commented on src/pages/private/sign-out/saga.js
> +    yield call(localStorageMethods.removeToken);
use axios

2021-08-05 08:51 UTC, zanusilker commented on src/pages/private/user-page/index.js
> +      { !initialized ? <Col><Spinner type="grow" color="info"/></Col>
```suggestion
      { initialized 
        ? <Col><Spinner type="grow" color="info"/></Col>
        : ...
```

2021-08-05 08:52 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +export const META = ACTION_TYPE.META;
```suggestion
```

2021-08-05 08:53 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +export const ACTION_TYPE = (prefix => ({
```suggestion
export const TYPE = (prefix => ({
```

2021-08-05 08:53 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +  INITIALIZE_APP: `${prefix}/INITIALIZE_APP`
```suggestion
```

2021-08-05 08:54 UTC, zanusilker commented on src/pages/private/user-page/reducer.js
> +
```suggestion
```

2021-08-05 08:54 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    if (token?.data?.accessToken) {
axios

2021-08-05 08:55 UTC, zanusilker commented on src/pages/public/reducer.js
> +import SingInReducer from './sign-in/reducer';
dependencies

2021-08-05 08:56 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +import { ReduxForm } from './redux-form';
dependencies

2021-08-05 08:56 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +      { errorMessage ? <Col>{ errorMessage }</Col> : null }
xs=12

2021-08-05 08:57 UTC, zanusilker commented on src/pages/public/sign-in/reducer.js
> +export const selector = state => state.pages.public.signIn;
is it action creators?

2021-08-05 08:58 UTC, zanusilker commented on src/pages/reducer.js
> +export const initializeApp = (() => ({ type: INITIALIZE_APP }));
```suggestion
export const initializeApp = () => ({ type: INITIALIZE_APP });
```

2021-08-05 08:59 UTC, zanusilker commented on src/pages/reducer.js
> +    case INITIALIZE:
```suggestion
```

2021-08-05 08:59 UTC, zanusilker commented on src/pages/reducer.js
> +import user from '../pages/private/reducer';
```suggestion
import private from '../pages/private/reducer';
```

2021-08-05 08:59 UTC, zanusilker commented on src/pages/reducer.js
> +import signIn from '../pages/public/reducer';
```suggestion
import public from '../pages/public/reducer';
```

2021-08-05 08:59 UTC, zanusilker commented on src/pages/reducer.js
> +  private: user,
```suggestion
  private,
```

2021-08-05 08:59 UTC, zanusilker commented on src/pages/saga.js
> +  yield takeEvery(INITIALIZE_APP, initializeSaga);
```suggestion
  yield takeEvery(INITIALIZE, initializeSaga);
```

2021-08-05 09:00 UTC, zanusilker commented on src/pages/saga.js
> +      yield put({ type: INITIALIZE, token: token.data.accessToken });
```suggestion
      yield put({ type: META, payload: { token: token.data.accessToken } });
```

2021-08-05 09:01 UTC, zanusilker commented on src/saga/index.js
> +  yield fork(watcherUser);
private/public

2021-08-05 09:02 UTC, zanusilker commented on src/utils.js
> +function setRefreshToken (data) {
where is access?

2021-08-06 11:26 UTC, zanusilker commented on src/pages/private/sign-out/reducer.js
> +const initialState = {
move to private

2021-08-06 11:27 UTC, zanusilker commented on src/pages/private/sign-out/reducer.js
> +export const signOut = () => ({ type: TYPE.INITIALIZE });
```suggestion
export const signOut = () => ({ type: TYPE.SIGN_OUT });
```

2021-08-06 11:28 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    yield put({ type: TYPE.META, payload: { errorMessage: error.message } });
use action creators

2021-08-06 11:31 UTC, zanusilker commented on src/services/api.js
> +    const refreshToken = token.data.refreshToken;
```suggestion
    token.data.refreshToken;
```

2021-08-06 14:11 UTC, Chernovolos commented on src/index.js
> +      newestOnTop={false}
default value true

2021-08-06 16:44 UTC, zanusilker commented on src/pages/index.js
> +//outsource dependencies
```suggestion
// outsource dependencies
```

2021-08-06 16:45 UTC, zanusilker commented on src/pages/private/user-page/index.js
> +      </Row>
```suggestion
      </Row> }
```

2021-08-06 16:45 UTC, zanusilker commented on src/pages/private/user-page/index.js
> +    { initialized ? <Row className="justify-content-center">
```suggestion
    { initialized 
    ? <Row className="justify-content-center">
```

2021-08-06 16:47 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    if (token?.data?.accessToken) {
![image](https://user-images.githubusercontent.com/16426586/128544391-b603cfb3-829e-4410-9d17-85e9e48629b9.png)

2021-08-06 16:49 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +    if (token?.data?.accessToken) {
https://app.prntscr.com/en/index.html

2021-08-06 16:51 UTC, zanusilker commented on src/pages/private/user-page/saga.js
> +  } finally {
why do you use finally?

2021-08-06 16:53 UTC, zanusilker commented on src/pages/public/saga.js
> +import userAuthorizationWatcher from '../public/sign-in/saga';
```suggestion
import userAuthorizationWatcher from './sign-in/saga';
```

2021-08-06 16:55 UTC, zanusilker commented on src/pages/public/saga.js
> +import initializeAppWatcher from '../saga';
```suggestion
```
use it in pages

2021-08-06 16:55 UTC, zanusilker commented on src/pages/public/sign-in/index.js
> +const FORM_NAME = 'sign-in-form';
use camel case notation

2021-08-06 16:57 UTC, zanusilker commented on src/pages/reducer.js
> +import publicReducer from '../pages/public/reducer';
```suggestion
import publicReducer from './public/reducer';
```

2021-08-06 16:57 UTC, zanusilker commented on src/pages/reducer.js
> +export const selector = (state) => state.pages;
```suggestion
export const selector = state => state.pages;
```

2021-08-06 16:58 UTC, zanusilker commented on src/pages/saga.js
> +      yield call(localStorageMethods.setToken, token);
```suggestion
```

2021-08-06 16:59 UTC, zanusilker commented on src/pages/saga.js
> +    yield call(history.push, ROUTES.SIGN_IN);
```suggestion
    yield call(history.push, ROUTES.SIGN_IN);
```
Do it in axios interceptor if you wasn't able to refresh token

2021-08-06 17:00 UTC, zanusilker commented on src/pages/saga.js
> +    yield put({ type: TYPE.CLEAR });
```suggestion
```

2021-08-06 17:04 UTC, zanusilker commented on src/services/api.js
> +  }
```suggestion
```

2021-08-06 17:07 UTC, zanusilker commented on src/services/api.js
> +let loop = 0;
why do you use it?

2021-08-09 13:02 UTC, merged